"""Initial DB

Revision ID: 17155e239338
Revises:
Create Date: 2019-06-16 22:52:47.950652

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '17155e239338'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uid', sa.Text(), nullable=True),
                    sa.Column('url', sa.Text(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
